Sprint 1
StepanenkoOlgaV/middle.messenger.praktikum.yandex pull request #2
Opened 2023-02-12 06:32 UTC by StepanenkoOlgaV

Выполнение задания 1 спринта.  
Используется компиляция и рендер на этапе сборки.
Макет взят предложенный Яндекс.Практикум с незначительными доработками (ссылка на figma размещена в README) .
Верстка предварительная:
- отображены не все состояния
- форма добавления файла отображается на странице редактирования информации о пользователе.

2023-02-12 13:06 UTC, podlovchenko requested changes
Привет, спасибо за проделанную работу, есть некоторые замечания
1. .github/workflows/tests.yml необходимо вернуть
2. По ссылке на нетлифай page not found

2023-02-12 13:06 UTC, podlovchenko commented on .nvmrc
> +v12.22.9
В проекте в некоторых файлах есть ошибка EOF
Для git важно наличие пустой строки в конце файла
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2023-02-12 13:06 UTC, podlovchenko commented on package.json
> +    "express": "^4.18.2",
В devDependencies указывается то, что необходимо для сборки и разработки приложения, в dependencies то, что необходимо непосредственно для работу приложения (express)

2023-02-12 13:06 UTC, podlovchenko commented on package.json
> +    "@anikin/parcel-transformer-handlebars": "^1.0.9",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2023-02-12 13:06 UTC, podlovchenko commented on src/static/styles/fileInput.pcss
> +.fileInput input[type=file] {
Лучше использовать классы, а не теги
Статья на эту тему https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2023-02-12 13:06 UTC, podlovchenko commented on src/static/styles/messagesBlock.pcss
> +    padding: 20px 10px 20px 10px;
Можно короче
```suggestion
    padding: 20px 10px;
```

2023-02-13 09:45 UTC, StepanenkoOlgaV commented on .nvmrc
> +v12.22.9
Исправила и прописала настройку files.insertFinalNewline в VSC

2023-02-14 04:03 UTC, StepanenkoOlgaV commented
- п 1 - вернула.
- п 2 - https://endearing-klepon-cdfcb6.netlify.app/ - настроила пока на ветку sprint_1, так как в deploy мы отправляем после ревью и заливки в main.  После первого мерджа в deploy поменяю.

2023-02-14 04:27 UTC, StepanenkoOlgaV commented on package.json
> +    "express": "^4.18.2",
Исправила

2023-02-14 04:27 UTC, StepanenkoOlgaV commented on package.json
> +    "@anikin/parcel-transformer-handlebars": "^1.0.9",
Исправила

2023-02-14 06:22 UTC, StepanenkoOlgaV commented on src/static/styles/button.pcss
> +    background-color: #3369f3;
Исправила

2023-02-14 06:25 UTC, StepanenkoOlgaV commented on src/static/styles/fileInput.pcss
> +.fileInput input[type=file] {
Исправила

2023-02-14 06:27 UTC, StepanenkoOlgaV commented on src/static/styles/messagesBlock.pcss
> +    padding: 20px 10px 20px 10px;
Исправила тут и в других местах проекта

2023-02-14 13:41 UTC, merged